# Generated by Django 3.1.7 on 2021-04-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsXP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportxp_user', models.CharField(default='', max_length=200)),
                ('last_performed_date', models.DateTimeField(verbose_name='date published')),
                ('basketball', models.IntegerField(default=0)),
                ('cross_training', models.IntegerField(default=0)),
                ('cardio', models.IntegerField(default=0)),
                ('strength_training', models.IntegerField(default=0)),
                ('climbing', models.IntegerField(default=0)),
                ('soccer', models.IntegerField(default=0)),
                ('american_football', models.IntegerField(default=0)),
                ('dance', models.IntegerField(default=0)),
                ('gymnastics', models.IntegerField(default=0)),
                ('hiking', models.IntegerField(default=0)),
                ('swimming', models.IntegerField(default=0)),
                ('yoga', models.IntegerField(default=0)),
            ],
        ),
    ]
