# Generated by Django 3.1.7 on 2021-04-11 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_feet', models.PositiveIntegerField(default=0)),
                ('height_inches', models.PositiveIntegerField(default=0)),
                ('weight_pounds', models.PositiveIntegerField(default=0)),
                ('time_of_bmi', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_bmi', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
