# Generated by Django 3.1.7 on 2021-04-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsxp',
            name='total_xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
