# Generated by Django 3.1.7 on 2021-04-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_user',
            field=models.TextField(default=''),
        ),
    ]
