# Generated by Django 3.1.7 on 2021-04-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_sportsxp_total_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsxp',
            name='total_xp',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
