# Generated by Django 3.1.7 on 2021-03-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.CharField(default=" feet' inches'' ", max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='MM/DD/YY', null=True),
        ),
    ]
