# Generated by Django 3.1.7 on 2021-04-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_sportsxp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsxp',
            name='sportxp_user',
        ),
        migrations.AlterField(
            model_name='sportsxp',
            name='last_performed_date',
            field=models.DateTimeField(verbose_name='date updated'),
        ),
    ]
