# Generated by Django 3.1.7 on 2021-04-08 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sportsxp',
            name='last_performed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
