# Generated by Django 3.1.7 on 2021-04-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20210408_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsxp',
            name='last_performed_date',
            field=models.DateTimeField(verbose_name='date updated'),
        ),
    ]
