# Generated by Django 3.1.7 on 2021-04-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20210408_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsxp',
            name='last_performed_date',
        ),
    ]
